[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](http://colab.research.google.com/github/jayunruh/python_introDS_course/blob/master/intro_to_python05_plotting.ipynb)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import scipy.stats as stats

## Loading the dataframe

In [2]:
df = pd.read_csv('https://www.dropbox.com/scl/fi/rirfgn0x25m32vtocvben/Lesson5b-B.csv?rlkey=ii8qcd914nbwbyy4u8r58tb1t&dl=1').dropna()
df

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,File,Area,Density1,Density2,Batch,Plate,Well,Object,PlateWell,Slide Number,Sample,Description1,Food,Time,Time (h)
0,11,232,81,./20240321_140300_322/Plate000_Well2_Object0.t...,3.341158,51.179857,54.172832,20240321_140300_322,0,2,0,000_2,Slide2,Artemina 10min,20296/H3P (FAM/Alexa555),Artemina,10min,0.166667
1,12,233,207,./20240321_140300_322/Plate000_Well2_Object1.t...,3.866314,30.520026,32.847825,20240321_140300_322,0,2,1,000_2,Slide2,Artemina 10min,20296/H3P (FAM/Alexa555),Artemina,10min,0.166667
2,13,236,263,./20240321_140300_322/Plate000_Well2_Object2.t...,3.158134,54.462533,57.628959,20240321_140300_322,0,2,2,000_2,Slide2,Artemina 10min,20296/H3P (FAM/Alexa555),Artemina,10min,0.166667
3,14,234,245,./20240321_140300_322/Plate000_Well2_Object3.t...,2.793080,31.864467,33.296578,20240321_140300_322,0,2,3,000_2,Slide2,Artemina 10min,20296/H3P (FAM/Alexa555),Artemina,10min,0.166667
4,15,231,78,./20240321_140300_322/Plate000_Well2_Object4.t...,3.516568,51.755009,53.461218,20240321_140300_322,0,2,4,000_2,Slide2,Artemina 10min,20296/H3P (FAM/Alexa555),Artemina,10min,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,287,32,184,./20240321_140300_322/Plate008_Well2_Object5.t...,1.892041,68.708883,71.880062,20240321_140300_322,8,2,5,008_2,Slide34,Peptone 7d,20296/H3P (FAM/Alexa555),Peptone,7d,168.000000
276,288,28,21,./20240321_140300_322/Plate008_Well2_Object6.t...,2.208097,97.821783,100.991933,20240321_140300_322,8,2,6,008_2,Slide34,Peptone 7d,20296/H3P (FAM/Alexa555),Peptone,7d,168.000000
277,289,31,107,./20240321_140300_322/Plate008_Well2_Object7.t...,1.789276,72.096183,76.008379,20240321_140300_322,8,2,7,008_2,Slide34,Peptone 7d,20296/H3P (FAM/Alexa555),Peptone,7d,168.000000
278,290,29,34,./20240321_140300_322/Plate008_Well2_Object8.t...,1.801154,62.737549,67.179145,20240321_140300_322,8,2,8,008_2,Slide34,Peptone 7d,20296/H3P (FAM/Alexa555),Peptone,7d,168.000000
279,291,35,274,./20240321_140300_322/Plate008_Well2_Object9.t...,1.826209,79.399467,84.327710,20240321_140300_322,8,2,9,008_2,Slide34,Peptone 7d,20296/H3P (FAM/Alexa555),Peptone,7d,168.000000

In [3]:
df['Food'].unique()

array(['Artemina', 'Liver', 'Peptone'], dtype=object)

In [4]:
df = df.replace({'Artemina':'Artemia'})

# Introduction to plotting

In [5]:
px.histogram(df, x='Area')

In [6]:
px.histogram(df, x='Area', width=400, title='Area of Planaria (um^2)', range_y=[0,50], color_discrete_sequence=['orange'])

In [7]:
px.density_heatmap(df, x='Area', y='Density1', width=500, height=400, title='Density of dividing cells vs Area of Planaria', color_continuous_scale='Viridis', labels={'Area':'Area of Planaria (um^2)', 'Density1':'Density of dividing cells'})

# Multi-dimensionality of plots

In [8]:
agged = df.groupby(['Time (h)', 'Time']).agg(Density1=('Density1', 'mean'), std=('Density1', 'std'), ).reset_index()
agged

      Time (h)   Time    Density1         std
0     0.166667  10min   79.543070   53.318009
1     2.000000     2h  301.179342  146.196876
2     4.000000     4h  435.142120  111.442017
3     6.000000     6h  314.784813   92.399404
4    24.000000     1d  248.249922  109.688727
5    48.000000     2d  267.091725  120.992714
6    72.000000     3d  233.884053  106.567419
7    96.000000     4d  156.385530   81.264231
8   120.000000     5d  114.885260   45.484648
9   144.000000     6d   85.896908   21.300319
10  168.000000     7d   93.295131   18.894722

In [9]:
px.bar(agged, x='Time', y='Density1', width=800)

In [10]:
px.line(agged, x='Time', y='Density1', markers=True, width=800, height=400, title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

In [11]:
px.line(agged, x='Time', y='Density1', markers=True, width=800, height=400, error_y='std', title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

In [12]:
agged = df.groupby(['Time (h)', 'Time', 'Food']).agg(Density1=('Density1', 'mean'), std=('Density1', 'std'),).reset_index()

In [13]:
px.line(agged, x='Time', y='Density1', markers=True, width=800, height=400, color='Food', error_y='std', title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})
# Note this is interactive, try clicking (or double clicking) on one of the Food types in the legend on the right

In [14]:
px.line(agged, x='Time', y='Density1', facet_col='Food', markers=True, width=800, height=400, error_y='std', title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

In [15]:
px.line(agged, x='Time', y='Density1', facet_row='Food', markers=True, width=800, height=800, error_y='std', title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

### ***Exercise:  See if you can make a plot which puts the different foods next to each other, but breaks out the times into separate plots using facet_col.  This gets to be a bit crowded, use px.bar? to see if there is an argument that can help tidy that up.

In [16]:
px.line(agged, x='Time', y='Density1', symbol='Food', markers=True, width=800, height=600, title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

In [17]:
px.line(agged, x='Time', y='Density1', animation_frame='Food', markers=True, width=800, height=600, error_y='std', title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

# Statistical plots

In [18]:
px.box(df, x='Time', y='Density1', color='Food')

Adding back some of our previous arguments, we also add two new ones:  hover_data and points

In [19]:
px.box(df, x='Time', y='Density1', color='Food', hover_data=['File'], points='all', width=1200, height=600, title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})

### ***Exercise:  Your PI hates box plots, they want you to make a violin plot instead.  They also want the range on the y-axis to be [0,1000]

# Exporting plots

In [20]:
f = px.box(df, x='Time', y='Density1', color='Food', hover_data=['File'], points='all', width=1200, height=600, title='Density of dividing cells vs Time since feeding',labels={'Time':'Time since feeding', 'Density1':'Density of dividing cells'})
f.write_html('Data/PlanariaBoxPlot.html')
f.write_image('Data/PlanariaBoxPlot.png', scale=2)
f.write_image('Data/PlanariaBoxPlot.pdf', scale=2)
f

In [21]:
!pip install -U kaleido

Requirement already satisfied: kaleido in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (1.0.0)
Requirement already satisfied: choreographer>=1.0.5 in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (from kaleido) (1.0.9)
Requirement already satisfied: logistro>=1.0.8 in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (from kaleido) (1.1.0)
Requirement already satisfied: orjson>=3.10.15 in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (from kaleido) (3.10.18)
Requirement already satisfied: packaging in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (from kaleido) (24.1)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\catseanjohn\miniforge3\envs\napari\lib\site-packages (from choreographer>=1.0.5->kaleido) (3.20.1)

## Statistical Tests

As there appears to be a large difference between Peptone and Liver at 2h and not one at 7d, we can perform a Mann Whitney test which makes no assumptions about the underlying data distributions.

In [22]:
density_2h_Peptone = df[(df['Food']=='Peptone') & (df['Time (h)']==2)]['Density1']
density_2h_Liver = df[(df['Food']=='Liver') & (df['Time (h)']==2)]['Density1']

stats.mannwhitneyu(density_2h_Peptone, density_2h_Liver)

MannwhitneyuResult(statistic=np.float64(64.0), pvalue=np.float64(0.0001554001554001554))

In [23]:
density_7d_Peptone = df[(df['Food']=='Peptone') & (df['Time']=='7d')]['Density1']
density_7d_Liver = df[(df['Food']=='Liver') & (df['Time']=='7d')]['Density1']

stats.mannwhitneyu(density_7d_Peptone, density_7d_Liver)

MannwhitneyuResult(statistic=np.float64(35.0), pvalue=np.float64(0.10066768749863966))

Since we know how to do loops, we can get the p-values for all Times/Foods.

In [24]:
times = ['10min', '2h', '4h', '6h', '1d', '2d', '3d', '4d', '5d', '6d', '7d']
foods = df[~(df['Food'].isin(['unfed', 'Liver']))]['Food'].unique()

p_values = []

for time in times:
    for food in foods:
        density_test = df[(df['Food']==food) & (df['Time']==time)]['Density1']
        density_liver = df[(df['Food']=='Liver') & (df['Time']==time)]['Density1']
        p_values.append([time, food, stats.mannwhitneyu(density_test, density_liver).pvalue])

p_values = np.array(p_values).reshape(11,2,3)        
p_values

array([[['10min', 'Artemia', '0.6453768453768453'],
        ['10min', 'Peptone', '8.227067050596462e-05']],

       [['2h', 'Artemia', '0.8784770784770783'],
        ['2h', 'Peptone', '0.0001554001554001554']],

       [['4h', 'Artemia', '0.006993006993006993'],
        ['4h', 'Peptone', '0.00032908268202385847']],

       [['6h', 'Artemia', '0.0037021801727684074'],
        ['6h', 'Peptone', '0.007897984368572603']],

       [['1d', 'Artemia', '0.08298368298368297'],
        ['1d', 'Peptone', '0.0001554001554001554']],

       [['2d', 'Artemia', '0.7209013209013208'],
        ['2d', 'Peptone', '0.0001554001554001554']],

       [['3d', 'Artemia', '0.020668220668220667'],
        ['3d', 'Peptone', '0.0003108003108003108']],

       [['4d', 'Artemia', '0.0029526029526029526'],
        ['4d', 'Peptone', '0.0001554001554001554']],

       [['5d', 'Artemia', '0.967435545139537'],
        ['5d', 'Peptone', '0.03596403596403597']],

       [['6d', 'Artemia', '0.6775849579524755'],
        ['6d', 'Peptone', '0.0007685389131627665']],

       [['7d', 'Artemia', '0.7426659029196823'],
        ['7d', 'Peptone', '0.10066768749863966']]], dtype='<U32')

p_values is now an 11X2X3 array:  Time X Food X Value (where the 3 values are the time, food, and pvalue).  Each row of this is effectively a DataFrame, so we can just concatenate them all together using a list comprehension and pd.concat.

In [25]:
pvalue_df = pd.concat([pd.DataFrame(p, columns=['Time', 'Food', 'p-value']) for p in p_values])
pvalue_df['p-value'] = pvalue_df['p-value'].astype(float).fillna(1)
pvalue_df['Significant'] = pvalue_df['p-value']<0.05

In [26]:
pvalue_df

    Time     Food   p-value  Significant
0  10min  Artemia  0.645377        False
1  10min  Peptone  0.000082         True
0     2h  Artemia  0.878477        False
1     2h  Peptone  0.000155         True
0     4h  Artemia  0.006993         True
1     4h  Peptone  0.000329         True
0     6h  Artemia  0.003702         True
1     6h  Peptone  0.007898         True
0     1d  Artemia  0.082984        False
1     1d  Peptone  0.000155         True
0     2d  Artemia  0.720901        False
1     2d  Peptone  0.000155         True
0     3d  Artemia  0.020668         True
1     3d  Peptone  0.000311         True
0     4d  Artemia  0.002953         True
1     4d  Peptone  0.000155         True
0     5d  Artemia  0.967436        False
1     5d  Peptone  0.035964         True
0     6d  Artemia  0.677585        False
1     6d  Peptone  0.000769         True
0     7d  Artemia  0.742666        False
1     7d  Peptone  0.100668        False

Or we can plot it using a scatter

In [27]:
px.scatter(pvalue_df, x='Time', y='Significant', facet_col='Food', width=600, title='Significance vs Liver')

# Melt and Pivot

## Melt

In our dataset the intensity has been measured at 2 different thresholds (Density1 and Density2).  If we want to see if these are yielding different results we can plot them side by side.  However plotly wants to plot y values only from one column of a table.  So we need to 'melt' our dataframe so that both Density1 and Density2 are in the same column, but we have an extra column that tells whether the value is a Density1 value or a Density2 value.

In [28]:
melted_df = df.melt(id_vars=['Food', 'Time (h)', 'Time', 'File'], value_vars=['Density1', 'Density2'], var_name='Density', value_name='Value')

In [29]:
print(melted_df.shape)
print(df.shape)

(560, 6)
(280, 18)

Our dataframe is twice as large, as now we have 2 entries for every file:  Density1 and Density2.  But now we can easily look at the results.

In [30]:
melted_df

,Food,Time (h),Time,File,Density,Value
0,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object0.t...,Density1,51.179857
1,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object1.t...,Density1,30.520026
2,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object2.t...,Density1,54.462533
3,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object3.t...,Density1,31.864467
4,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object4.t...,Density1,51.755009
...,...,...,...,...,...,...
555,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object5.t...,Density2,71.880062
556,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object6.t...,Density2,100.991933
557,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object7.t...,Density2,76.008379
558,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object8.t...,Density2,67.179145
559,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object9.t...,Density2,84.327710

Now we can plot them side by side:  Density1 and Density2

In [31]:
px.box(melted_df, x='Time', y='Value', points='all', color='Density')

We are more interested in seeing it if impacts our conclusion about the Food/Time relationship.  So we choose a multi-dimensional argument (facet_col, color, animation_frame, etc.) to let us look at the two values side by side.

animation_frame is nice for this task as we want to be able to flip between the two thresholds to see if it changes our conclusions in any way.

In [32]:
px.box(melted_df, x='Time', y='Value', points='all', color='Food', range_x=[-0.5,11.5], range_y=[0, 750], width=1200, height=600, title='Dividing Cell Density Over Time By Food', 
       color_discrete_map={'unfed':'black', 'Liver':'magenta', 'Peptone':'orange', 'Artemina':'blue'}, category_orders={'Food':['unfed', 'Liver', 'Artemina', 'Peptone']}, animation_frame='Density')

## Pivot

Now let's say our measurements come from an ImageJ results table, where measurements for each channel are in a separate row, but we would like to combine them into a single row per measurement.  This is basically what we have with our melted_df, so let's do a backwards melt() operation.

In [33]:
melted_df

,Food,Time (h),Time,File,Density,Value
0,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object0.t...,Density1,51.179857
1,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object1.t...,Density1,30.520026
2,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object2.t...,Density1,54.462533
3,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object3.t...,Density1,31.864467
4,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object4.t...,Density1,51.755009
...,...,...,...,...,...,...
555,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object5.t...,Density2,71.880062
556,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object6.t...,Density2,100.991933
557,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object7.t...,Density2,76.008379
558,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object8.t...,Density2,67.179145
559,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object9.t...,Density2,84.327710

In [34]:
normal_df = melted_df.pivot(index=['Food', 'Time (h)', 'Time', 'File'], columns='Density', values='Value').reset_index()
normal_df.columns = ['Food', 'Time (h)', 'Time', 'File', 'Density1', 'Density2']
normal_df

,Food,Time (h),Time,File,Density1,Density2
0,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object0.t...,51.179857,54.172832
1,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object1.t...,30.520026,32.847825
2,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object2.t...,54.462533,57.628959
3,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object3.t...,31.864467,33.296578
4,Artemia,0.166667,10min,./20240321_140300_322/Plate000_Well2_Object4.t...,51.755009,53.461218
...,...,...,...,...,...,...
275,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object5.t...,68.708883,71.880062
276,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object6.t...,97.821783,100.991933
277,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object7.t...,72.096183,76.008379
278,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object8.t...,62.737549,67.179145
279,Peptone,168.000000,7d,./20240321_140300_322/Plate008_Well2_Object9.t...,79.399467,84.327710